import path from 'node:path'
import { localIso } from './time.js'
import type { Diagnostic } from './diagnostics.js'
import { diag } from './diagnostics.js'
import { exists, readTextIfExists, writeText } from './fsx.js'
import { defaultConfig, writeConfig } from './config.js'
import { ensureSddDirs } from './workspace.js'
import { templatesFor } from './templates.js'
import { detectProfiles, detectionToYaml, loadProfilesFromDir, type DetectionResult } from './profiles.js'
import type { Language } from './model.js'

export interface InitOptions {
  root: string
  name?: string
  language?: Language
  local?: boolean
  profilesDir?: string
  now?: Date
}

export interface InitResult {
  sddDir: string
  created: string[]
  detected?: DetectionResult
  diagnostics: Diagnostic[]
}

export async function initWorkspace(opts: InitOptions): Promise<InitResult> {
  const root = path.resolve(opts.root)
  const sddDir = path.join(root, '.sdd')
  const diagnostics: Diagnostic[] = []
  const created: string[] = []

  if (await exists(path.join(sddDir, 'config.yaml'))) {
    return {
      sddDir,
      created,
      diagnostics: [diag('ATLAS-INIT-001', 'error', 'El proyecto ya está inicializado (.sdd/config.yaml existe)', { path: sddDir, suggestion: 'No hace falta volver a ejecutar `satlas init`' })],
    }
  }

  created.push(...(await ensureSddDirs(sddDir)))

  const language: Language = opts.language ?? 'es'
  const cfg = defaultConfig({ name: opts.name, language })
  cfg.project.name = opts.name ?? path.basename(root)
  await writeConfig(sddDir, cfg)
  created.push(path.join(sddDir, 'config.yaml'))

  const templates = templatesFor(language)
  await writeText(path.join(sddDir, 'constitution.md'), templates.constitution)
  created.push(path.join(sddDir, 'constitution.md'))
  await writeText(path.join(sddDir, 'glossary.md'), templates.glossary)
  created.push(path.join(sddDir, 'glossary.md'))

  const detected = await detectIfPossible(root, opts.profilesDir)
  if (detected) {
    const yaml = detectionToYaml(detected, localIso(opts.now))
    await writeText(path.join(sddDir, 'profiles', 'detected.yaml'), yaml)
    created.push(path.join(sddDir, 'profiles', 'detected.yaml'))
    if (detected.best) {
      diagnostics.push(diag('ATLAS-INIT-002', 'info', `Stack detectado: ${detected.best.displayName} (${detected.best.score} puntos)`, { suggestion: 'Revisa .sdd/profiles/detected.yaml' }))
    } else {
      diagnostics.push(diag('ATLAS-INIT-003', 'info', 'No se detectó un stack conocido: se usará el perfil genérico', { suggestion: 'Crea un perfil propio con `satlas profile` (F2) o edita .sdd/profiles/custom/' }))
    }
  }

  await writeText(path.join(sddDir, 'INDEX.md'), initialIndex(language, cfg.project.name))
  created.push(path.join(sddDir, 'INDEX.md'))

  if (opts.local) {
    const gitignore = path.join(root, '.gitignore')
    const current = (await readTextIfExists(gitignore)) ?? ''
    if (!/(^|\n)\.sdd\/?(\n|$)/.test(current)) {
      const next = current.endsWith('\n') || current === '' ? `${current}.sdd/\n` : `${current}\n.sdd/\n`
      await writeText(gitignore, next)
      created.push(gitignore)
    }
  }

  return detected ? { sddDir, created, detected, diagnostics } : { sddDir, created, diagnostics }
}

async function detectIfPossible(root: string, profilesDir?: string): Promise<DetectionResult | undefined> {
  if (!profilesDir) return undefined
  if (!(await exists(profilesDir))) return undefined
  const profiles = await loadProfilesFromDir(profilesDir)
  if (profiles.length === 0) return undefined
  return detectProfiles(root, profiles)
}

function initialIndex(language: Language, projectName: string): string {
  const es = language !== 'en'
  return `# Índice — ${projectName}\n\n${es ? '> Generado por SpecAtlas. Las specs vivas y los cambios se listan aquí a medida que existan.' : '> Generated by SpecAtlas.'}\n\n${es ? '## Specs vivas\n\n_Sin specs todavía._' : '## Living specs\n\n_No specs yet._'}\n\n${es ? '## Cambios activos\n\n_Sin cambios activos._' : '## Active changes\n\n_No active changes._'}\n\n${es ? '## Archivados\n\n0 cambio(s) en `changes/archive/`.' : '## Archived\n\n0 change(s).'}\n`
}
